Output assets/cli-demo-neofetch.gif

Require "/usr/local/bin/baeru"
Require neofetch

Set Shell "bash"
Set FontSize 20
Set Width 1200
Set Height 760
Set Framerate 30
Set Padding 24
Set CursorBlink false
Set TypingSpeed 40ms

# Debian
Type "baeru neofetch --ascii_distro debian"
Enter
Sleep 3s

# Ubuntu
Type "baeru neofetch --ascii_distro ubuntu"
Enter
Sleep 3s

# Redhat
Type "baeru neofetch --ascii_distro redhat"
Enter
Sleep 3s

# CentOS
Type "baeru neofetch --ascii_distro centos"
Enter
Sleep 3s

# Arch
Type "baeru neofetch --ascii_distro arch"
Enter
Sleep 3s
